//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlickrSlideshow_1._0.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("72157716671842277")]
        public string defaultGalleryId {
            get {
                return ((string)(this["defaultGalleryId"]));
            }
            set {
                this["defaultGalleryId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double defaultTransitionTimeInSeconds {
            get {
                return ((double)(this["defaultTransitionTimeInSeconds"]));
            }
            set {
                this["defaultTransitionTimeInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double defaultAnimationTimeInSeconds {
            get {
                return ((double)(this["defaultAnimationTimeInSeconds"]));
            }
            set {
                this["defaultAnimationTimeInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double minTransitionTimeInSeconds {
            get {
                return ((double)(this["minTransitionTimeInSeconds"]));
            }
            set {
                this["minTransitionTimeInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double minAnimationTimeInSeconds {
            get {
                return ((double)(this["minAnimationTimeInSeconds"]));
            }
            set {
                this["minAnimationTimeInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default Gallery")]
        public string defaultGalleryName {
            get {
                return ((string)(this["defaultGalleryName"]));
            }
            set {
                this["defaultGalleryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.flickr.com/photos/flickr/galleries")]
        public string flikrGalleryBrowserUrl {
            get {
                return ((string)(this["flikrGalleryBrowserUrl"]));
            }
            set {
                this["flikrGalleryBrowserUrl"] = value;
            }
        }
    }
}
